server:
  port: 8181


broker:
  host: localhost
  port: 61616
  username: artemis
  password: artemis

spring:
  datasource:
    url: jdbc:h2:mem:messages_db
    driver-class-name: org.h2.Driver
  jpa:
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

